In [ ]:
from google.colab import drive
drive.mount('/content/drive')

%cd  /content/drive/'My Drive'/dfc2021-msd-baseline-master

Mounted at /content/drive
/content/drive/My Drive/dfc2021-msd-baseline-master


In [ ]:
!pip install rasterio fiona segmentation-models-pytorch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 19.3 MB 535 kB/s 
     |████████████████████████████████| 16.7 MB 46.4 MB/s 
     |████████████████████████████████| 97 kB 7.7 MB/s 
     |████████████████████████████████| 58 kB 7.5 MB/s 
     |████████████████████████████████| 376 kB 45.0 MB/s 
  Created wheel for efficientnet-pytorch: filename=efficientnet_pytorch-0.7.1-py3-none-any.whl size=16446 sha256=8bc4306a208d2a00df04a3a3f75d9739d02324457493d404801cb5bd1f02da0a
  Stored in directory: /root/.cache/pip/wheels/0e/cc/b2/49e74588263573ff778da58cc99b9c6349b496636a7e165be6
  Created wheel for pretrainedmodels: filename=pretrainedmodels-0.7.4-py3-none-any.whl size=60965 sha256=246e40b7b6f363a3a778f1c5bcbc51eff50b6b767874d387bdfdc16d536e1cf2
  Stored in directory: /root/.cache/pip/wheels/ed/27/e8/9543d42de2740d3544db96aefef63bda3f2c1761b3334f4873
Successfully built efficientnet-pytorch pretrainedmo

In [ ]:
#!pip install pytorch torchvision

In [ ]:
!python train.py --input_fn data/splits/training_set_naip_nlcd_both_sample.csv --output_dir results/unet_both_baseline/ --save_most_recent --num_epochs 1

Starting DFC2021 baseline training script at 2022-11-09 00:44:34.363028
The output directory doesn't exist or is empty.
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:566: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
We will be training with 62 batches per epoch
Model has 11780305 parameters
64it [02:07,  1.99s/it]
[] Training Epoch: 0	 Time elapsed: 127.37 seconds	 Loss: 1.32


In [ ]:
!python inference.py --input_fn data/splits/val_inference_both_sample.csv --model_fn results/unet_both_baseline/most_recent_model.pt --output_dir results/unet_both_baseline/output/


Starting DFC2021 model inference script at 2022-11-09 00:47:06.565608
The output directory doesn't exist or is empty.
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:566: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
(0/10) Processing https://dfc2021.blob.core.windows.net/competition-data/naip-2013/2283_naip-2013.tif ... finished in 21.3552 seconds
(1/10) Processing https://dfc2021.blob.core.windows.net/competition-data/naip-2017/2283_naip-2017.tif ... finished in 19.1488 seconds
(2/10) Processing https://dfc2021.blob.core.windows.net/competition-data/naip-2013/2449_naip-2013.tif ... finished in 25.0568 seconds
(3/10) Processing https:

In [ ]:
!python independent_pairs_to_predictions.py --input_dir results/unet_both_baseline/output/ --output_dir results/unet_both_baseline/submission/


Starting to combine predictions at 2022-11-09 00:51:04.334534
The output directory doesn't exist or is empty.
(0/5) Processing tile 2283 ... finished in 0.3761 seconds
(1/5) Processing tile 2449 ... finished in 0.4408 seconds
(2/5) Processing tile 2448 ... finished in 0.4050 seconds
(3/5) Processing tile 2003 ... finished in 0.4055 seconds
(4/5) Processing tile 2002 ... finished in 0.4047 seconds


NICFI

In [ ]:
!python train.py --input_fn data/splits/data_both_sample.csv --output_dir results/unet_both_baseline_nicfi/ --save_most_recent --num_epochs 1

Starting DFC2021 baseline training script at 2022-11-15 05:03:48.417859
The output directory doesn't exist or is empty.
/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py:566: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
We will be training with 25 batches per epoch
Model has 11780305 parameters
  0% 0/25 [00:00<?, ?it/s]/usr/local/lib/python3.7/dist-packages/rasterio/__init__.py:220: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
/usr/local/lib/python3.7/dist-packages/rasterio/__init__.py:220: NotGeoreferencedWarnin

In [ ]:
!python inference.py --input_fn data/splits/val_inference_both_sample.csv --model_fn results/unet_both_baseline_nicfi/most_recent_model.pt --output_dir results/unet_both_baseline_nicfi/output/


In [ ]:
img= '/content/drive/MyDrive/GEE_Dynamic_2016_three_class/0_0.jpeg'
with rasterio.open(img) as f:
  data = f.read()

data.shape

/usr/local/lib/python3.7/dist-packages/rasterio/__init__.py:220: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)


(3, 3899, 3897)

In [ ]:
!pip install rasterio
import rasterio

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np

a = np.array([[1,0],[2,1]])
b = np.array([[1,0],[2,5]])

a*b

array([[1, 0],
       [4, 5]])

##Checking Dataloader


In [ ]:
import sys

import numpy as np

import rasterio
from rasterio.windows import Window
from rasterio.errors import RasterioError, RasterioIOError

import torch 
from torchvision import transforms
from torch.utils.data.dataset import IterableDataset

class StreamingGeospatialDataset(IterableDataset):
    
    def __init__(self, imagery_fns, label_fns=None, groups=None, chip_size=256, num_chips_per_tile=200, windowed_sampling=False, image_transform=None, label_transform=None, nodata_check=None, verbose=False):
        """A torch Dataset for randomly sampling chips from a list of tiles. When used in conjunction with a DataLoader that has `num_workers>1` this Dataset will assign each worker to sample chips from disjoint sets of tiles.

        Args:
            imagery_fns: A list of filenames (or URLS -- anything that `rasterio.open()` can read) pointing to imagery tiles.
            label_fns: A list of filenames of the same size as `imagery_fns` pointing to label mask tiles or `None` if the Dataset should operate in "imagery only mode". Note that we expect `imagery_fns[i]` and `label_fns[i]` to have the same dimension and coordinate system.
            groups: Optional: A list of integers of the same size as `imagery_fns` that gives the "group" membership of each tile. This can be used to normalize imagery from different groups differently.
            chip_size: Desired size of chips (in pixels).
            num_chips_per_tile: Desired number of chips to sample for each tile.
            windowed_sampling: Flag indicating whether we should sample each chip with a read using `rasterio.windows.Window` or whether we should read the whole tile into memory, then sample chips.
            image_transform: A function to apply to each image chip object. If this is `None`, then the only transformation applied to the loaded imagery will be to convert it to a `torch.Tensor`. If this is not `None`, then the function should return a `Torch.tensor`. Further, if `groups` is not `None` then the transform function should expect the imagery as the first argument and the group as the second argument.
            label_transform: Similar to image_transform, but applied to label chips.
            nodata_check: A method that will check an `(image_chip)` or `(image_chip, label_chip)` (if `label_fns` are provided) and return whether or not the chip should be skipped. This can be used, for example, to skip chips that contain nodata values.
            verbose: If `False` we will be quiet.
        """

        if label_fns is None:
            self.fns = imagery_fns
            self.use_labels = False
        else:
            self.fns = list(zip(imagery_fns, label_fns)) 
            self.use_labels = True

        self.groups = groups

        self.chip_size = chip_size
        self.num_chips_per_tile = num_chips_per_tile
        self.windowed_sampling = windowed_sampling

        self.image_transform = image_transform
        self.label_transform = label_transform
        self.nodata_check = nodata_check

        self.verbose = verbose

        if self.verbose:
            print("Constructed StreamingGeospatialDataset")

    def stream_tile_fns(self):
        worker_info = torch.utils.data.get_worker_info()
        if worker_info is None: # In this case we are not loading through a DataLoader with multiple workers
            worker_id = 0
            num_workers = 1
        else:
            worker_id = worker_info.id
            num_workers = worker_info.num_workers

        # We only want to shuffle the order we traverse the files if we are the first worker (else, every worker will shuffle the files...)
        if worker_id == 0:
            np.random.shuffle(self.fns) # in place
        # NOTE: A warning, when different workers are created they will all have the same numpy random seed, however will have different torch random seeds. If you want to use numpy random functions, seed appropriately.
        #seed = torch.randint(low=0,high=2**32-1,size=(1,)).item()
        #np.random.seed(seed) # when different workers spawn, they have the same numpy random seed...

        if self.verbose:
            print("Creating a filename stream for worker %d" % (worker_id))

        # This logic splits up the list of filenames into `num_workers` chunks. Each worker will recieve ceil(num_filenames / num_workers) filenames to generate chips from. If the number of workers doesn't divide the number of filenames evenly then the last worker will have fewer filenames.
        N = len(self.fns)
        num_files_per_worker = int(np.ceil(N / num_workers))
        lower_idx = worker_id * num_files_per_worker
        upper_idx = min(N, (worker_id+1) * num_files_per_worker)
        for idx in range(lower_idx, upper_idx):

            label_fn = None
            if self.use_labels:
                img_fn, label_fn = self.fns[idx]
            else:
                img_fn = self.fns[idx]

            if self.groups is not None:
                group = self.groups[idx]
            else:
                group = None

            if self.verbose:
                print("Worker %d, yielding file %d" % (worker_id, idx))

            yield (img_fn, label_fn, group)

    def stream_chips(self):
        for img_fn, label_fn, group in self.stream_tile_fns():
            num_skipped_chips = 0

            # Open file pointers
            img_fp = rasterio.open(img_fn, "r")
            label_fp = rasterio.open(label_fn, "r") if self.use_labels else None

            height, width = img_fp.shape
            if self.use_labels: # garuntee that our label mask has the same dimensions as our imagery
                t_height, t_width = label_fp.shape
                assert height == t_height and width == t_width


            # If we aren't in windowed sampling mode then we should read the entire tile up front
            img_data = None
            label_data = None
            try:
                if not self.windowed_sampling:
                    img_data = np.rollaxis(img_fp.read(), 0, 3)
                    if self.use_labels:
                        label_data = label_fp.read().squeeze() # assume the label geotiff has a single channel
            except RasterioError as e:
                print("WARNING: Error reading in entire file, skipping to the next file")
                continue

            for i in range(self.num_chips_per_tile):
                # Select the top left pixel of our chip randomly
                x = np.random.randint(0, width-self.chip_size)
                y = np.random.randint(0, height-self.chip_size)

                # Read imagery / labels
                img = None
                labels = None
                if self.windowed_sampling:
                    try:
                        img = np.rollaxis(img_fp.read(window=Window(x, y, self.chip_size, self.chip_size)), 0, 3)
                        print(img.shape)
                        if self.use_labels:
                            labels = label_fp.read(window=Window(x, y, self.chip_size, self.chip_size)).squeeze()
                    except RasterioError:
                        print("WARNING: Error reading chip from file, skipping to the next chip")
                        continue
                else:
                    img = img_data[y:y+self.chip_size, x:x+self.chip_size, :]
                    if self.use_labels:
                        labels = label_data[y:y+self.chip_size, x:x+self.chip_size]

                # Check for no data
                if self.nodata_check is not None:
                    if self.use_labels:
                        skip_chip = self.nodata_check(img, labels)
                    else:
                        skip_chip = self.nodata_check(img)

                    if skip_chip: # The current chip has been identified as invalid by the `nodata_check(...)` method
                        num_skipped_chips += 1
                        continue

                # Transform the imagery
                if self.image_transform is not None:
                    if self.groups is None:
                        img = self.image_transform(img)
                    else:
                        img = self.image_transform(img, group)
                else:
                    img = torch.from_numpy(img).squeeze()

                # Transform the labels
                if self.use_labels:
                    if self.label_transform is not None:
                        if self.groups is None:
                            labels = self.label_transform(labels)
                        else:
                            labels = self.label_transform(labels, group)
                    else:
                        labels = torch.from_numpy(labels).squeeze()


                # Note, that img should be a torch "Double" type (i.e. a np.float32) and labels should be a torch "Long" type (i.e. np.int64)
                if self.use_labels:
                    yield img, labels
                else:
                    yield img

            # Close file pointers
            img_fp.close()
            if self.use_labels:
                label_fp.close()

            if num_skipped_chips>0 and self.verbose:
                print("We skipped %d chips on %s" % (img_fn))

    def __iter__(self):
        if self.verbose:
            print("Creating a new StreamingGeospatialDataset iterator")
        return iter(self.stream_chips())


In [ ]:
NAIP_2013_MEANS = np.array([83.18, 79.00, 55.65])
NAIP_2013_STDS = np.array([13.83,  9.16, 10.09])
NAIP_2017_MEANS = np.array([80.80, 79.22, 54.69])
NAIP_2017_STDS = np.array([9.35 , 5.94, 6.79])

def image_transforms(img, group):
    if group == 0:
        img = (img - NAIP_2013_MEANS) / NAIP_2013_STDS
    elif group == 1:
        img = (img - NAIP_2017_MEANS) / NAIP_2017_STDS
    else:
        raise ValueError("group not recognized")
    img = np.rollaxis(img, 2, 0).astype(np.float32)
    img = torch.from_numpy(img)
    return img

def label_transforms(labels, group):
    labels = utils.NLCD_CLASS_TO_IDX_MAP[labels]
    labels = torch.from_numpy(labels)
    return labels

In [ ]:
import pandas as pd

input_dataframe = pd.read_csv('data/splits/data_both_sample.csv')
image_fns = input_dataframe["image_fn"].values
label_fns = input_dataframe["label_fn"].values
groups = input_dataframe["group"].values

training_set_naip_nlcd_both_sample

In [ ]:
image_fns

array(['/content/drive/MyDrive/GEE_regen/00.tif',
       '/content/drive/MyDrive/GEE_2019_final/00.tif',
       '/content/drive/MyDrive/GEE_regen/02.tif',
       '/content/drive/MyDrive/GEE_2019_final/01.tif',
       '/content/drive/MyDrive/GEE_regen/01.tif',
       '/content/drive/MyDrive/GEE_2019_final/04.tif',
       '/content/drive/MyDrive/GEE_regen/03.tif',
       '/content/drive/MyDrive/GEE_2019_final/03.tif'], dtype=object)

In [ ]:
label_fns

array(['/content/drive/MyDrive/GEE_Dynamic_2016_three_class/0_0.jpeg',
       '/content/drive/MyDrive/GEE_Dynamic_2019_three_class/0_0.jpeg',
       '/content/drive/MyDrive/GEE_Dynamic_2016_three_class/0_2.jpeg',
       '/content/drive/MyDrive/GEE_Dynamic_2019_three_class/0_1.jpeg',
       '/content/drive/MyDrive/GEE_Dynamic_2016_three_class/0_1.jpeg',
       '/content/drive/MyDrive/GEE_Dynamic_2019_three_class/0_4.jpeg',
       '/content/drive/MyDrive/GEE_Dynamic_2016_three_class/0_3.jpeg',
       '/content/drive/MyDrive/GEE_Dynamic_2019_three_class/0_3.jpeg'],
      dtype=object)

In [ ]:
dataset = StreamingGeospatialDataset(
        imagery_fns=image_fns, label_fns=label_fns, groups=groups, chip_size=256, num_chips_per_tile=100, windowed_sampling=False, verbose=False,
        image_transform=image_transforms, label_transform=None, nodata_check=None
    )

In [ ]:
dataloader = torch.utils.data.DataLoader(
        dataset,
        batch_size=32,
        num_workers=4,
        pin_memory=True,
    )

In [ ]:
dataloader

In [ ]:
import models
import segmentation_models_pytorch as smp
import torch.optim as optim
import torch.nn as nn
import torch.nn.functional as F
import os
import utils

num_training_batches_per_epoch = int(len(image_fns) * 100 / 32)
print("We will be training with %d batches per epoch" % (num_training_batches_per_epoch))


if torch.cuda.is_available():
        device = torch.device("cuda", 0)

model = models.get_unet()


model = smp.Unet(
        encoder_name='resnet18', encoder_depth=3, encoder_weights=None,
        decoder_channels=(128, 64, 64), in_channels=4, classes=16)
optimizer = optim.AdamW(model.parameters(), lr=0.001, amsgrad=True)
criterion = nn.CrossEntropyLoss()
scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, "min")

We will be training with 62 batches per epoch


In [ ]:
training_task_losses = []
num_times_lr_dropped = 0 
model_checkpoints = []
temp_model_fn = os.path.join('results/unet_both_baseline_nicfi/', "most_recent_model.pt")

for epoch in range(1):
    lr = utils.get_lr(optimizer)

    training_losses = utils.fit(
        model,
        device,
        dataloader,
        num_training_batches_per_epoch,
        optimizer,
        criterion,
        epoch,
    )
    scheduler.step(training_losses[0])

    model_checkpoints.append(copy.deepcopy(model.state_dict()))
    #if args.save_most_recent:
    torch.save(model.state_dict(), temp_model_fn)

    if utils.get_lr(optimizer) < lr:
        num_times_lr_dropped += 1
        print("")
        print("Learning rate dropped")
        print("")
        
    training_task_losses.append(training_losses[0])
        
    if num_times_lr_dropped == 4:
        break

  0%|          | 0/25 [00:00<?, ?it/s]

/usr/local/lib/python3.7/dist-packages/rasterio/__init__.py:220: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
/usr/local/lib/python3.7/dist-packages/rasterio/__init__.py:220: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
/usr/local/lib/python3.7/dist-packages/rasterio/__init__.py:220: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
/usr/local/lib/python3.7/dist-packages/rasterio/__init__.py:220: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)


  0%|          | 0/25 [00:04<?, ?it/s]


RuntimeError: ignored

In [138]:
img_fp = rasterio.open('/content/drive/MyDrive/GEE_regen/00.tif', "r")
height, width = img_fp.shape
print(height, width)

label_fp = rasterio.open('/content/drive/MyDrive/GEE_Dynamic_2016_three_class/0_0.jpeg', "r")
#label_fp = rasterio.open('/content/drive/MyDrive/GEE_Dynamic_2016_three_class_np_label/0_0.npy', "r")
t_height, t_width = label_fp.shape
print(t_height, t_width)

3899 3897
3899 3897


/usr/local/lib/python3.7/dist-packages/rasterio/__init__.py:220: NotGeoreferencedWarning: Dataset has no geotransform, gcps, or rpcs. The identity matrix be returned.
  s = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)


In [ ]:
img_data = np.rollaxis(img_fp.read(), 0, 3)

label_data = label_fp.read().squeeze() # assume the label geotiff has a single channel

label_data.shape

(3, 3899, 3897)

In [ ]:
'''
img_fp = rasterio.open('https://dfc2021.blob.core.windows.net/competition-data/naip-2013/546_naip-2013.tif', "r")
height, width = img_fp.shape
print(height, width)

label_fp = rasterio.open('https://dfc2021.blob.core.windows.net/competition-data/nlcd-2013/546_nlcd-2013.tif', "r")
t_height, t_width = label_fp.shape
print(t_height, t_width)
'''

3880 3880
3880 3880


In [ ]:
'''
img_data = np.rollaxis(img_fp.read(), 0, 3)

label_data = label_fp.read().squeeze() # assume the label geotiff has a single channel

label_data.shape
'''

(3880, 3880)

In [ ]:
img = img_data[0:256, 0:256, :]

labels = label_data[0:256, 0:256]


NAIP_2013_MEANS = np.array([117.00, 130.75, 122.50, 159.30])
NAIP_2013_STDS = np.array([38.16, 36.68, 24.30, 66.22])
NAIP_2017_MEANS = np.array([72.84,  86.83, 76.78, 130.82])
NAIP_2017_STDS = np.array([41.78, 34.66, 28.76, 58.95])

img=image_transforms(img,0)
labels = label_transforms(labels, 0)

In [ ]:
labels

tensor([[10, 10, 10,  ...,  8,  8,  8],
        [10, 10, 10,  ...,  8,  8,  8],
        [ 3,  3, 10,  ...,  8,  8,  8],
        ...,
        [ 8,  8,  8,  ...,  8,  8,  8],
        [ 8,  8,  8,  ...,  8,  8,  8],
        [ 8,  8,  8,  ...,  8,  8,  8]])

In [ ]:
label_data[0]

array([43, 43, 43, ..., 81, 81, 81], dtype=uint8)

In [ ]:
NLCD_CLASSES = [ 0, 11, 12, 21, 22, 23, 24, 31, 41, 42, 43, 52, 71, 81, 82, 90, 95]

def get_nlcd_class_to_idx_map():
    nlcd_label_to_idx_map = []
    idx = 0
    for i in range(NLCD_CLASSES[-1]+1):
        if i in NLCD_CLASSES:
            nlcd_label_to_idx_map.append(idx)
            idx += 1
        else:
            nlcd_label_to_idx_map.append(0)
    nlcd_label_to_idx_map = np.array(nlcd_label_to_idx_map).astype(np.int64)
    return nlcd_label_to_idx_map

NLCD_CLASS_TO_IDX_MAP = get_nlcd_class_to_idx_map()

def label_transforms(labels, group):
    labels = NLCD_CLASS_TO_IDX_MAP[labels]
    labels = torch.from_numpy(labels)
    return labels

In [ ]:
label_transforms(labels, 0)

IndexError: ignored

In [ ]:
NLCD_CLASS_TO_IDX_MAP

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  0,  0,  0,  0,
        0,  0,  0,  0,  3,  4,  5,  6,  0,  0,  0,  0,  0,  0,  7,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  8,  9, 10,  0,  0,  0,  0,  0,  0,  0,
        0, 11,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, 12,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13, 14,  0,  0,
        0,  0,  0,  0,  0, 15,  0,  0,  0,  0, 16])

In [ ]:
hp = {}
for i in label_data[0]:
  if i in hp:
    hp[i]+=1
  else:
    hp[i]=1

hp

{43: 122, 21: 93, 41: 2773, 52: 62, 71: 711, 81: 88, 31: 31}

In [ ]:
hp = {}
for i in label_data[0][0]:
  if i in hp:
    hp[i]+=1
  else:
    hp[i]=1

hp

{57: 2565,
 50: 6,
 58: 7,
 69: 4,
 60: 5,
 42: 7,
 55: 5,
 98: 2,
 144: 2,
 193: 43,
 210: 7,
 204: 8,
 197: 12,
 199: 8,
 196: 847,
 190: 8,
 225: 1,
 224: 2,
 222: 4,
 221: 1,
 215: 2,
 208: 10,
 186: 10,
 171: 2,
 156: 1,
 141: 1,
 129: 1,
 118: 1,
 110: 2,
 107: 2,
 111: 1,
 121: 1,
 128: 1,
 63: 68,
 23: 1,
 26: 1,
 65: 7,
 93: 3,
 85: 2,
 68: 10,
 95: 1,
 27: 3,
 37: 1,
 61: 4,
 71: 3,
 38: 2,
 46: 1,
 97: 2,
 167: 1,
 219: 1,
 243: 1,
 182: 2,
 200: 9,
 183: 4,
 179: 6,
 192: 3,
 207: 4,
 206: 5,
 214: 6,
 189: 3,
 162: 1,
 178: 4,
 201: 9,
 213: 4,
 203: 3,
 194: 8,
 230: 1,
 174: 3,
 106: 1,
 43: 4,
 79: 2,
 56: 3,
 49: 4,
 54: 5,
 36: 3,
 53: 3,
 78: 2,
 74: 3,
 47: 7,
 45: 3,
 90: 2,
 155: 2,
 217: 5,
 187: 5,
 202: 4,
 226: 3,
 109: 2,
 35: 2,
 185: 2,
 176: 2,
 209: 1,
 164: 3,
 67: 1,
 99: 1,
 168: 2,
 205: 2,
 231: 1,
 102: 3,
 25: 1,
 70: 3,
 80: 2,
 77: 1,
 91: 1,
 89: 2,
 29: 2,
 170: 1,
 140: 1,
 211: 2,
 218: 1,
 184: 1,
 108: 1,
 40: 1,
 81: 3,
 32: 2,
 39: 1,
 10

In [ ]:
label_data[0]

array([[ 57,  57,  57, ..., 196, 196, 196],
       [ 57,  57,  57, ..., 196, 196, 196],
       [ 57,  57,  57, ..., 196, 196, 196],
       ...,
       [ 57,  57,  57, ...,  58,  58,  58],
       [ 57,  57,  57, ...,  47,  47,  47],
       [ 57,  57,  57, ...,  51,  51,  51]], dtype=uint8)

In [ ]:
img_data[0]

array([[53, 62, 39],
       [51, 61, 39],
       [51, 61, 39],
       ...,
       [59, 63, 44],
       [59, 64, 44],
       [59, 64, 44]], dtype=uint8)

In [ ]:
label_data.shape

(3, 3899, 3897)

In [ ]:
#NLCD

In [ ]:
label_data[0]

array([43, 43, 43, ..., 81, 81, 81], dtype=uint8)

In [ ]:
img_data[0]

array([[ 81,  81,  95, 173],
       [ 82,  86,  95, 178],
       [ 81,  87,  95, 183],
       ...,
       [112, 126, 117, 224],
       [102, 118, 114, 224],
       [109, 130, 116, 226]], dtype=uint8)

In [ ]:
label_data[0][0]

array([ 57,  57,  57, ..., 196, 196, 196], dtype=uint8)